# Generated by Django 3.2.8 on 2021-10-22 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0003_auto_20211022_1624'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='distribuidor',
            new_name='idDistribuidor',
        ),
    ]
