# Generated by Django 3.2.8 on 2021-11-25 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0005_producto_disponible'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='disponible',
            field=models.BooleanField(default=True),
        ),
    ]
