# Generated by Django 3.2.8 on 2021-11-25 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0006_alter_producto_disponible'),
    ]

    operations = [
        migrations.AddField(
            model_name='distribuidor',
            name='disponible',
            field=models.BooleanField(default=True),
        ),
    ]
