version: '3.9'

services:
  db:
    image: postgres
    volumes:
      - ./data/db:\Program Files\PostgreSQL\14\data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=2365
  web:
    build: .
    command: python carroDeCompras/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db



  
  