# Generated by Django 3.2.8 on 2021-11-29 20:30

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductosComprados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30, unique=True)),
                ('descripcion', models.CharField(max_length=100, unique=True)),
                ('claveProductoOriginal', models.IntegerField()),
                ('precioVenta', models.FloatField(max_length=20)),
                ('cantidad', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30, unique=True)),
                ('apellido', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=60)),
                ('clave', models.CharField(max_length=30)),
                ('tipo', models.BooleanField()),
                ('disponible', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ventas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaDeVenta', models.DateField()),
                ('precioTotal', models.FloatField()),
                ('idProductoComprado', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='carro.productoscomprados')),
            ],
        ),
        migrations.AddField(
            model_name='productoscomprados',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='carro.usuario'),
        ),
        migrations.CreateModel(
            name='CarrosCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listaProductos', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), size=None)),
                ('cantidad_de_producto', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None)),
                ('precioTotal', models.FloatField()),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='carro.usuario')),
            ],
        ),
    ]
