# Generated by Django 3.2.8 on 2021-10-28 01:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carro', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ventas',
            name='idProductoComprado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='carro.productoscomprados'),
        ),
    ]
