# Generated by Django 3.2.8 on 2021-11-29 21:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carro', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productoscomprados',
            name='usuario',
            field=models.ForeignKey(default=0, null=True, on_delete=django.db.models.deletion.SET_NULL, to='carro.usuario'),
        ),
        migrations.AlterField(
            model_name='ventas',
            name='idProductoComprado',
            field=models.ForeignKey(default=0, null=True, on_delete=django.db.models.deletion.SET_NULL, to='carro.productoscomprados'),
        ),
    ]
