# Generated by Django 3.2.9 on 2021-11-24 00:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carro', '0002_ventas_idproductocomprado'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Clientes',
        ),
        migrations.RemoveField(
            model_name='carroscompra',
            name='cantidad_de_cada_producto',
        ),
        migrations.RemoveField(
            model_name='carroscompra',
            name='listado_de_productos',
        ),
        migrations.AddField(
            model_name='carroscompra',
            name='cantidad_de_producto',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='carroscompra',
            name='producto',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='productoscomprados',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='carro.usuario'),
        ),
        migrations.AlterField(
            model_name='carroscompra',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='carro.usuario'),
        ),
        migrations.AlterField(
            model_name='ventas',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='carro.usuario'),
        ),
    ]
