# Generated by Django 3.2.8 on 2021-11-30 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carro', '0003_auto_20211129_2235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productoscomprados',
            name='descripcion',
            field=models.CharField(max_length=100),
        ),
    ]
