# Generated by Django 3.2.8 on 2021-11-25 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carro', '0003_auto_20211123_2120'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='disponible',
            field=models.BooleanField(default=True),
        ),
    ]
