# Generated by Django 3.2.9 on 2021-11-30 20:41

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carro', '0004_usuario_disponible'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetalleVentas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productosId', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(default=0), size=None)),
                ('cantidad', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(default=0), size=None)),
                ('precioTotal', models.FloatField()),
                ('fechaDeVenta', models.DateField(default='2021-11-30')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='carro.usuario')),
            ],
        ),
        migrations.RemoveField(
            model_name='ventas',
            name='idProductoComprado',
        ),
        migrations.RemoveField(
            model_name='ventas',
            name='usuario',
        ),
        migrations.DeleteModel(
            name='ProductosComprados',
        ),
        migrations.DeleteModel(
            name='Ventas',
        ),
    ]
