# Generated by Django 3.2.9 on 2021-12-07 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carro', '0005_auto_20211130_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalleventas',
            name='fechaDeVenta',
            field=models.DateField(default='2021-12-07'),
        ),
    ]
