# Generated by Django 3.2.9 on 2021-12-09 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carro', '0006_alter_detalleventas_fechadeventa'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carroscompra',
            old_name='producto',
            new_name='productos',
        ),
        migrations.AlterField(
            model_name='detalleventas',
            name='fechaDeVenta',
            field=models.DateField(default='2021-12-09'),
        ),
    ]
