# Generated by Django 3.2.9 on 2021-12-10 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carro', '0007_auto_20211209_2332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carroscompra',
            name='usuario',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='detalleventas',
            name='fechaDeVenta',
            field=models.DateField(default='2021-12-10'),
        ),
    ]
