# Generated by Django 3.2.8 on 2021-12-13 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carro', '0008_auto_20211210_1213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalleventas',
            name='fechaDeVenta',
            field=models.DateField(default='2021-12-13'),
        ),
    ]
