# Generated by Django 3.2.9 on 2021-12-21 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carro', '0009_alter_detalleventas_fechadeventa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalleventas',
            name='fechaDeVenta',
            field=models.DateField(default='2021-12-21'),
        ),
    ]
