# Generated by Django 3.2.8 on 2021-10-07 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carroscompra',
            name='precioTotal',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='telefono',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='productoscomprados',
            name='cantidad',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='ventas',
            name='precioTotal',
            field=models.FloatField(),
        ),
    ]
